### ISSUE TITLE
Using in Linux

### ISSUE THREAD

**Issue by mclang** [evilC/IOWrapper#29]
I try to most of my gaming in Linux.

Should I try this and UCR-C# on my Linux box, or is it time wasted?
Would trying with Mono or with Dotnet be better bet to get this working?

**Comment by evilC** [comment]
At the moment, IOWrapper / UCR are Windows only.  
Everything is .NET Framework, which is not cross-platform.  
At some point we want to move to .NET Core, which is cross-platform, however even if that happens, we would need providers for IOWrapper that supported linux.  
The most commonly used input providers (DirectInput and XInput) would be pointless on Linux I think, as they don't exist, and as far as output providers go (eg vJoy), do they even exist?  
I think it would be possible to write a generic HID provider that was cross-platform though.  
Of course, if you have any abilities in this area, you are most welcome to pitch in and help out with the conversion.

**Comment by mclang** [comment]
I wish I had the time to help :(

I happened to stumble upon this tough:
http://qjoypad.sourceforge.net

Maybe the code in that helps if somebody has the time to check this out.
